Audits `XrpSignerListSet` Protobuf Wrapper
xpring-eng/Xpring-JS pull request #752
Opened 2020-09-29 20:09 UTC by mvadari

## High Level Overview of Change

This PR adds additional logic validations and descriptive error throwing to the class `XrpSignerListSet`.

### Context of Change

Another component of our attempt to make protobuf wrapper classes as safe and informative as possible. An SDK safety net.

### Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Before / After

`XrpSignerListSet` performs logic/error checking, based on the business logic in the docs.

## Test Plan

New tests added to confirm that errors are correctly thrown. Existing tests were edited to properly account for the new errors. CI passes.

## Future Tasks
This is part of a series, with all subtasks listed here: https://app.asana.com/0/1188384817180008/1193021408531788/f

2020-09-30 21:44 UTC, tedkalaw requested changes
looks p good, some thoughts inline

2020-09-30 21:44 UTC, tedkalaw commented on src/XRP/model/xrp-signer-list-set.ts
> +    if (signerQuorum == undefined) {
`===`

2020-09-30 21:44 UTC, tedkalaw commented on src/XRP/model/xrp-signer-list-set.ts
> +      if (signerEntries.length > 8) {
const for this value? could be a file-scoped const

2020-09-30 21:44 UTC, tedkalaw commented on src/XRP/model/xrp-signer-list-set.ts
> +        const signerAccount = signerEntry.accountXAddress
extreme naming nit - `signerAccountXAddress`?

2020-09-30 21:44 UTC, tedkalaw commented on src/XRP/model/xrp-signer-list-set.ts
> +      if (signerEntries.length == 0) {
`===`

2020-09-30 21:44 UTC, tedkalaw commented on src/XRP/model/xrp-signer-list-set.ts
> +      const accounts: string[] = []
can we use a `Set` here instead?

2020-10-01 18:54 UTC, tedkalaw approved these changes

2020-10-01 23:18 UTC, amiecorso approved these changes

2020-10-01 23:18 UTC, amiecorso commented on src/XRP/model/xrp-signer-list-set.ts
> +        'SignerListSet protobuf does not contain `SignerQuorum` field.',
lowercase

2020-10-02 16:47 UTC, merged