Corrects falsiness assumptions
xpring-eng/Xpring-JS pull request #753
Opened 2020-09-29 21:48 UTC by mvadari

## High Level Overview of Change

When converting from GRPC classes to Typescript classes, the code often uses `if (!field)` to determine if an object is undefined. However, this catches other falsey cases as well, such as if the field equals `0` or `""`. This PR corrects those assumptions where needed. 

### Context of Change

This was noticed while auditing all the Typescript wrapper classes.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Before / After

Falsiness assumptions have been corrected. 

## Test Plan

CI passes. 

## Future Tasks
More corrections will be made in future auditing PRs.

2020-09-30 13:52 UTC, amiecorso approved these changes
great catch on this

2020-09-30 16:46 UTC, tedkalaw requested changes
can we use the `===` operators here instead of `==`? this should technically work because undefined is only equal to itself but afaik we don't use type coercion in the sdk for these checks

2020-09-30 16:46 UTC, tedkalaw commented on src/XRP/model/xrp-account-set.ts
> +      setFlag != undefined &&
`!==` please

2020-09-30 16:46 UTC, tedkalaw commented on src/XRP/model/xrp-currency-amount.ts
> +    if (xrpAmount != undefined && issuedCurrencyAmount == undefined) {
same with these `===` and `!==`

2020-10-01 18:50 UTC, tedkalaw approved these changes

2020-10-01 18:59 UTC, merged