add fee to transaction as option
xpring-eng/Xpring-JS pull request #924
Opened 2020-11-24 00:33 UTC by ledhed2222

## High Level Overview of Change

Add `fee` as an option when sending XRP

### Context of Change

https://app.asana.com/0/1190398011050052/1199238264596125/f

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

Just adds a new optional param when sending XRP.

Looks like a bunch of `eslint` changes from our tests are included. Just adding them too.

## Test Plan

Added one unit test to make sure that we can get transaction responses back. DID NOT verify that transactions will fail with a very small fee amount.

2020-11-24 00:34 UTC, ledhed2222 commented on src/Xpring/xpring-client.ts
> +      ...sendXrpDetails,
these changes will make it unnecessary to change this function unless you have to pre-process a member of `SendXrpDetails`.

2020-11-24 00:35 UTC, ledhed2222 commented on test/XRP/default-xrp-client.test.ts
> +
this is the only thing added in the test suite that wasn't an eslint fix

2020-11-25 20:23 UTC, mvadari reviewed
I think your eslint is on the wrong settings or something - when I open up the branch locally, it wants to undo all of the eslint-related changes you make here. 

Looks good other than that

2020-11-30 19:45 UTC, amiecorso requested changes
I think this looks good so far.  I'm not really sure what's going on with the linting changes... since several of us have been contributing to these files recently without any such changes being invoked by the linter...  But I'm not sure how to fix it.

I think we might want to add an integration test here that 1) queries the ledger for the current required minimum fee and then 2) submits a transaction where maxfee is set higher than this (success) and potentially lower than this (failure) ?

2020-11-30 19:45 UTC, amiecorso commented on test/XRP/default-xrp-client.test.ts
> +    // THEN the transaction hash exists and finds the transaction with the memo.
```suggestion
    // THEN the transaction hash exists and is as expected.
```

2020-12-02 00:11 UTC, mvadari requested changes

2020-12-02 00:11 UTC, mvadari commented on test/ILP/fakes/fake-ilp-network-client.ts
> +    public readonly sendResponse: Response<SendPaymentResponse> = FakeIlpNetworkClientResponses.defaultSendResponse(),
Unrelated change (also covered in #941 )

2020-12-02 00:11 UTC, mvadari commented on test/PayID/pay-id-integration.test.ts
> +  it('Resolve PayID to XRP - known PayID - mainnet', async function (): Promise<void> {
Same with all the changes in this file

2020-12-02 00:11 UTC, mvadari commented on test/XRP/fakes/fake-web-socket-network-client.ts
> +    public readonly getGatewayBalancesResponse: Result<GatewayBalancesResponse> = FakeWebSocketNetworkClientResponses.defaultGetGatewayBalancesResponse(),
same

2020-12-02 00:11 UTC, mvadari commented on test/XRP/fakes/fake-xrp-network-client.ts
> +    public readonly getTransactionHistoryResponse: Result<GetAccountTransactionHistoryResponse> = FakeXRPNetworkClientResponses.defaultGetTransactionHistoryResponse(),
same

2021-03-23 01:58 UTC, closed without merging